### ISSUE TITLE
Add v0.5.3 tag

### ISSUE THREAD

**Issue by shmel1k** [tarantool-php/client#50]
Hi!
Can you push tag v0.5.3 from current master with persistent connections so I could add it to my composer? :)
Now when I do install I get 0.5.2 version without persistent connections :(

ps: maybe I am doing something wrong because I am total php noob)

**Comment by rybakit** [comment]
Hi!
It can't be 0.5.3 because of the breaking changes in some interfaces and classes, so the next version will be 0.6.0. However, before releasing 0.6.0 I plan to do some more breaking changes, that's is why there is no new release yet :) In meanwhile, you can install the latest dev version with

```bash
composer require tarantool/client:@dev
```
By the way, if you are new to php, I wouldn't recommend using persistent connections until you 100% sure how they work and what are the side effects of using them. What are you trying to solve with persistent connections?

**Comment by shmel1k** [comment]
highload stuff(dont ask why php :))
something like 2k requests per second and tcp-handshake is not possible for us. 
Found https://www.php.net/manual/ru/features.persistent-connections.php, but I think we can allow this side-effects.
