### ISSUE TITLE
Is syn checked[help wanted]

### ISSUE THREAD

**Issue by shmel1k** [tarantool-php/client#51]
Hello, I one more question from me :)
Is 'SYN' checked somehow? How do we ensure that the request returned from Tarantool is returned for the client requested it? 
I could not find code that checks this kind of behavior. Thanks in advance!

**Comment by rybakit** [comment]
Good question :) Initially, the sync check was not necessary because the client sends requests synchronously, but for persistent connections that have been added recently, there may indeed be a case where the client sends a request and dies right before reading a response, which will lead to a wrong response on a next request.

**Comment by shmel1k** [comment]
Oh, thanks) I wanted to implement that myself, but you were faster). Are you going to merge this into master-branch?

**Comment by rybakit** [comment]
Yep, I will merge it soon.
