### ISSUE TITLE
PeclLitePacker failed on authentificate response

### ISSUE THREAD

**Issue by podbelsky** [tarantool-php/client#6]
There are an error while unpacking authentificate response:

> PHP Fatal error:  Cannot use object of type stdClass as array in ***/vendor/tarantool/client/src/Packer/PeclLitePacker.php on line 53

PeclPacker (not Lite) works fine.

PHP 5.6.19 (cli) (built: Mar  3 2016 08:05:32)
tarantool/client  v0.1.0

**Comment by rybakit** [comment]
To make it work, set `msgpack.php_only` ini setting to `0`. But you should really use `PeclPacker` instead of `PeclLitePacker` if you have the msgpack-php extension installed.

`PeclLitePacker` was written for hhvm msgpack extension, which doesn’t have all functionality the php version has (literally, it only has `msgpack_pack`/`msgpack_unpack` functions). That is why I called it "Lite", but probably I should rename it to something less confusing.
